//
//  AllTimeRun.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import UIKit
import AWSDynamoDB

class AllTimeRun: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _date: NSNumber?
    var _address: String?
    var _city: String?
    var _country: String?
    var _distance: NSNumber?
    var _duration: NSNumber?
    var _energy: NSNumber?
    var _notes: String?
    var _pace: NSNumber?
    var _route: Set<NSNumber>?
    var _weather: String?
    
    class func dynamoDBTableName() -> String {

        return "stepbystep-mobilehub-138898687-AllTimeRun"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_date"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable : Any]{
        return [
               "_userId" : "userId",
               "_date" : "date",
               "_address" : "address",
               "_city" : "city",
               "_country" : "country",
               "_distance" : "distance",
               "_duration" : "duration",
               "_energy" : "energy",
               "_notes" : "notes",
               "_pace" : "pace",
               "_route" : "route",
               "_weather" : "weather",
        ]
    }
}
