//
//  WeeklyRanking.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//

import Foundation
import UIKit
import AWSDynamoDB

class WeeklyRanking: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _week: NSNumber?
    var _appear: NSNumber?
    var _distance: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "stepbystep-mobilehub-138898687-WeeklyRanking"
    }
    
    class func hashKeyAttribute() -> String {

        return "_week"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_userId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable : Any] {
        return [
               "_userId" : "userId",
               "_week" : "week",
               "_appear" : "appear",
               "_distance" : "distance",
        ]
    }
}
