//
//  AWSConfiguration.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.8
//
//

import AWSCore


// Cognito User Pools Identity Id
let AWSCognitoUserPoolId: String = "us-east-1_usesPjotD"

// Cognito User Pools App Client Id
let AWSCognitoUserPoolAppClientId: String = "cjrd5017norcn3thjp6j63mge"

// Cognito User Pools Region
let AWSCognitoUserPoolRegion: AWSRegionType = .usEast1

// Cognito User Pools Client Secret
let AWSCognitoUserPoolClientSecret: String = "b7e05kei8gbt9f1h8og398mfdh7pquim0nkdji9l2t13jo4v4mm"
